version: '3.6'
services:
  landing:
    build:
      context: "./"
      dockerfile: Dockerfile
    networks:
      - porto
    environment:
      APP_ENV: development
    volumes:
      - "./src:/app/src"
    ports:
      - "3000:3000"

networks:
  porto:
    name: dzikri_portfolio_network